// Writes the README's error-code table (between the error-codes markers) from src/errors.ts, so the
// table a developer reads is the one the code uses. `--check` exits 1 if the README is stale (a test
// runs it too).
//
//   npx tsx scripts/error-table.ts          write
//   npx tsx scripts/error-table.ts --check  check

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { ERROR_CODES, messageFor, REVERT_CODES } from "../src/errors.js";

export function errorTable(): string {
  const byCode: Record<string, string[]> = {};
  for (const [name, code] of Object.entries(REVERT_CODES)) (byCode[code] ??= []).push(`\`${name}\``);
  const rows = ERROR_CODES.map((code) => `| \`${code}\` | ${(byCode[code] ?? []).join(", ") || "—"} | ${messageFor(code).replace(/\|/g, "\\|")} |`);
  return ["| Code | Contract errors | Default `userMessage` |", "|---|---|---|", ...rows].join("\n");
}

const BEGIN = "<!-- error-codes:begin (generated by scripts/error-table.ts) -->";
const END = "<!-- error-codes:end -->";

export function renderReadme(readme: string): string {
  const start = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (start < 0 || end < 0) throw new Error("README.md has no error-codes markers");
  return `${readme.slice(0, start + BEGIN.length)}\n${errorTable()}\n${readme.slice(end)}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const path = fileURLToPath(new URL("../README.md", import.meta.url));
  const readme = readFileSync(path, "utf8");
  const next = renderReadme(readme);
  if (process.argv.includes("--check")) {
    if (next !== readme) {
      console.error("README.md's error-code table is stale: run `npm run docs:errors`.");
      process.exit(1);
    }
    console.log("README error-code table current.");
  } else {
    writeFileSync(path, next);
  }
}
