// Writes src/abi/*.ts from the Foundry artifacts under the repository's out/ directory, so the
// library is typed against exactly the ABIs `forge build` produces. Run `forge build` first.
//
//   node scripts/gen-abis.mjs           write the files
//   node scripts/gen-abis.mjs --check   exit 1 if any checked-in file differs (the CI drift check)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, "..");
const repo = join(pkg, "..", "..");
const out = join(repo, "out");
const target = join(pkg, "src", "abi");

// [artifact, export name, file name]
const CONTRACTS = [
  ["MintABear", "mintABearAbi", "mintABear.ts"],
  ["WhitelistClaim", "whitelistClaimAbi", "whitelistClaim.ts"],
  ["Activation", "activationAbi", "activation.ts"],
  ["SeaDrop", "seaDropAbi", "seaDrop.ts"],
];

function render(artifact, name) {
  const path = join(out, `${artifact}.sol`, `${artifact}.json`);
  if (!existsSync(path)) {
    throw new Error(`${relative(repo, path)} not found: run \`forge build\` at the repository root first`);
  }
  const { abi } = JSON.parse(readFileSync(path, "utf8"));
  return (
    `// Generated by scripts/gen-abis.mjs from out/${artifact}.sol/${artifact}.json. Do not edit.\n` +
    `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
}

function renderIndex() {
  return (
    "// Generated by scripts/gen-abis.mjs. Do not edit.\n" +
    CONTRACTS.map(([, name, file]) => `export { ${name} } from "./${file.replace(/\.ts$/, ".js")}";\n`).join("")
  );
}

const check = process.argv.includes("--check");
const files = [
  ...CONTRACTS.map(([artifact, name, file]) => [file, render(artifact, name)]),
  ["index.ts", renderIndex()],
];

const stale = [];
for (const [file, content] of files) {
  const path = join(target, file);
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) stale.push(relative(pkg, path));
  } else {
    writeFileSync(path, content);
  }
}

if (check) {
  if (stale.length > 0) {
    console.error(`ABI drift: ${stale.join(", ")} differ from out/. Run \`npm run gen:abi\` and commit.`);
    process.exit(1);
  }
  console.log(`ABIs current (${CONTRACTS.length} contracts).`);
} else {
  console.log(`Wrote ${files.length} files to ${relative(pkg, target)}.`);
}
